# vim: set et ts=4:
tricks:
- watchdog.tricks.ShellCommandTrick:
    patterns: ["*/js/*.coffee"]
    shell_command: "reset;make js"
- watchdog.tricks.ShellCommandTrick:
    #TODO: shouldn't need leading "*" below...
    patterns: ["*/tests/*.coffee"]
    shell_command: "make test"
# - watchdog.tricks.LoggerTrick:
#     patterns: ["*/tests/*.coffee"]
